#define IDD_DIALOG_EARLIER_FW_FOUND			9000
#define IDC_CHECKBOX_REMOVE_SHORTCUTS		9001
#define IDC_CHECKBOX_UNINSTALL_EARLIER_FW	9002

#define EARLIER_FW_REMOVE_SHORTCUTS		1
#define EARLIER_FW_UNINSTALL			2
