//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resources.rc
//
#define IDD_DIALOG_DISPLAY_REPORT			101
#define IDD_DIALOG_REBOOT_COUNTDOWN			102
#define IDD_DIALOG_MAIN_PRODUCT_SELECT		103
#define IDD_DIALOG_STATUS					104
#define IDD_DIALOG_NO_ANIMATION_STATUS		105
#define IDD_DIALOG_PAUSE_FOR_REBOOT			106
#define IDR_MAIN_ICON						107
#define BACKGROUND_BMP						108

#define IDC_EDIT_REPORT						1000
#define IDC_STATIC_REPORT_INTRO				1001
#define IDC_STATIC_STATUS_MAIN				1002
#define IDC_STATIC_STATUS_SUB				1003
#define IDC_STATIC_STATUS_3RD				1004
#define IDC_BUTTON_MORE_DETAILS				1005
#define IDC_STATIC_REBOOT_COUNTDOWN			1006
#define IDC_BUTTON_PAUSE_RESUME				1007
#define IDC_ANIMATE_STATUS					1008
#define IDC_BUTTON_MAIN_HELP				1009
#define IDC_BUTTON_TERMS					1010
#define IDC_BUTTON_REENTER_KEY				1011
#define IDC_BUTTON_CONTINUE					1012
#define IDC_BUTTON_HIDDEN1					1013
#define IDC_BUTTON_HIDDEN2					1014

#define IDC_ERROR								5000
#define IDC_ERROR_IS_FATAL						5001
#define IDC_ERROR_INTERNAL						5002
#define IDC_ERROR_PREREQUISITE_FAIL				5003
#define IDC_ERROR_PREREQUISITE_PRIOR_FAIL		5004
#define IDC_ERROR_DEPENDENT_INTRO				5005
#define IDC_ERROR_DEPENDENT_INSTRUCTION			5006
#define IDC_ERROR_DEPENDENT_WILD_GUESS			5007
#define IDC_ERROR_NEED_ADMIN_ACCESS				5008
#define IDC_ERROR_NEED_BETTER_OS				5009
#define IDC_ERROR_NEED_WORSE_OS					5010
#define IDC_ERROR_CORRUPT_RECORD				5011
#define IDC_ERROR_USER_ABORT					5012
#define IDC_ERROR_KEY_DLL						5013
#define IDC_ERROR_INSTALLATION					5014
#define IDC_ERROR_USER_QUIT_INSTALLER			5015
#define IDC_ERROR_FILE_MISSING_URL				5016
#define IDC_ERROR_FILE_MISSING					5017
#define IDC_ERROR_READ_REG						5018
#define IDC_ERROR_WRITE_REG						5019
#define IDC_ERROR_REMOVE_REG					5020
#define IDC_ERROR_REBOOT_FAILED					5021
#define IDC_ERROR_CREATE_STATUS_DLG				5022
#define IDC_ERROR_INSTALL_NEVER					5023
#define IDC_ERROR_INSTALL_ERROR					5024
#define IDC_ERROR_INSTALL_INTERRUPTED			5025
#define IDC_ERROR_INSTALL_USER_SKIP				5026
#define IDC_ERROR_INSTALL_NEED_BETTER_OS		5027
#define IDC_ERROR_INSTALL_NEED_WORSE_OS			5028
#define IDC_ERROR_INSTALL_NEED_ADMIN			5029
#define IDC_ERROR_INSTALL_FILE_NOT_FOUND		5030
#define IDC_ERROR_INSTALL_FILE_NOT_FOUND_EXTRA	5031
#define IDC_ERROR_INSTALL_PREREQUISITES			5032
#define IDC_ERROR_LOG_FILE_INVALID				5033
#define IDC_ERROR_TOO_MANY_KEY_GUESSES			5034
#define IDC_ERROR_LANGUAGE_INCOMPATIBLE			5035
#define IDC_ERROR_LANGUAGE_INCOMPATIBLE_1		5036
#define IDC_ERROR_LANGUAGE_INCOMPATIBLE_2		5037
#define IDC_ERROR_LANGUAGE_INCOMPATIBLE_URL		5038
#define IDC_ERROR_OS_VERSION_LIE_VISTA			5039

#define IDC_MESSAGE_INSTRUCTIONS			6000
#define IDC_MESSAGE_INSERT					6001
#define IDC_MESSAGE_NOTHING_SELECTED		6002
#define IDC_MESSAGE_INITIALIZING			6003
#define IDC_MESSAGE_TEST_HANGING			6004
#define IDC_MESSAGE_INSTALLING				6005
#define IDC_MESSAGE_EVALUATING				6006
#define IDC_MESSAGE_DEPENDENCIES			6007
#define IDC_MESSAGE_REMAINING				6008
#define IDC_MESSAGE_RETRY_INSTRUCTIONS		6009
#define IDC_MESSAGE_FINISHED				6010
#define IDC_MESSAGE_PENDING_REBOOT			6011
#define IDC_MESSAGE_CONFIRM_SKIP			6012
#define IDC_MESSAGE_SKIPORCANCEL			6013
#define IDC_MESSAGE_PREREQUISITES			6014
#define IDC_MESSAGE_PREREQUISITE_INTRO		6015
#define IDC_MESSAGE_HANGING_WINDOWS_INTRO_1	6016
#define IDC_MESSAGE_HANGING_WINDOWS_INTRO_2	6017
#define IDC_MESSAGE_REQUIREMENTS			6018
#define IDC_MESSAGE_REQUIREMENT_INTRO		6019
#define IDC_MESSAGE_CONFIRM_QUIT			6020
#define IDC_MESSAGE_CONFIRM_QUIT_GENERAL	6021
#define IDC_MESSAGE_BASIC_LIST				6022
#define IDC_MESSAGE_MORE_DETAILS			6023
#define IDC_MESSAGE_CONFIRM_QUIT_REBOOT		6024
#define IDC_MESSAGE_ALREADY_INSTALLED		6025
#define IDC_MESSAGE_UPGRADE_READY			6026
#define IDC_MESSAGE_DOWNGRADE_DANGER		6027
#define IDC_MESSAGE_UPGRADE_TOO_LATE		6028
#define IDC_MESSAGE_CONFIRM_QUIT_MAIN		6029
#define IDC_MESSAGE_CONFIRM_QUIT_WHOLE		6030
#define IDC_MESSAGE_QUITTING_P				6031
#define IDC_MESSAGE_QUITTING				6032
#define IDC_MESSAGE_GENERIC_INSTALLER		6033
#define IDC_MESSAGE_PAUSE					6034
#define IDC_MESSAGE_RESUME					6035
#define IDC_MESSAGE_REQUIRED_SOFTWARE		6036
#define IDC_MESSAGE_NEEDED_BY				6037
#define IDC_MESSAGE_NOTHING_UNLOCKED		6038
#define IDC_MESSAGE_PRODUCT_NOT_INSTALLED	6039
#define IDC_MESSAGE_LOG_IN_CLIPBOARD		6040
#define IDC_MESSAGE_CONTINUE				6041
#define	IDC_MESSAGE_MORE_PREREQUISITES		6042
#define	IDC_MESSAGE_MORE_REQUIREMENTS		6043
#define IDC_MESSAGE_CONSEQUENCES			6044
#define IDC_MESSAGE_NEED_BETTER_OS			6045
#define IDC_MESSAGE_NEED_WORSE_OS			6046
#define IDC_MESSAGE_NEED_ADMIN_PRIV			6047
#define IDC_MESSAGE_MUST_WAIT				6048
#define IDC_MESSAGE_ANSI_ERROR				6049
#define IDC_MESSAGE_INSTALLATION_PAUSED		6050
#define IDC_MESSAGE_SET_LANGUAGE1			6051
#define IDC_MESSAGE_SET_LANGUAGE2			6052

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1012
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
