// TestPresenceWebControl.idl : type library source for ActiveX Control project.

// This file will be processed by the MIDL compiler tool to
// produce the type library (TestPresenceWebControl.tlb) that will become a resource in
// TestPresence Web Control.ocx.

#include <olectl.h>
#include <idispids.h>

//[ uuid(AE8C2C7F-401F-4BAD-8F9F-4EA46E65C2E3), version(1.0),
[ uuid(17FB0E4C-6CD2-4ee7-A361-BBD437229D47), version(1.0),
  helpfile("TestPresence Web Control.hlp"),
  helpstring("TestPresence Web Control ActiveX Control module"),
  control ]
library TestPresenceWebControlLib
{
	importlib(STDOLE_TLB);

	//  Primary dispatch interface for CTestPresenceCtrl

	[ uuid(F1749565-CE5C-472c-8041-8F4864C24A57),
	  helpstring("Dispatch interface for TestPresence Control")]
	dispinterface _DTestPresenceWebControl
	{
		properties:
		methods:
			[id(1), helpstring("method TestPresence")] VARIANT_BOOL TestPresence(BSTR Tag, BSTR MinVersion, BSTR MaxVersion);
			[id(2), helpstring("method GetOsVersionString")] BSTR GetOsVersionString(void);
	};

	//  Class information for CTestPresenceCtrl
	[ uuid(3BF3E3EB-97DB-40d4-937E-4E548D1FCE90),
	  helpstring("TestPresence Control"), control ]
	coclass TestPresenceWebControl
	{
		[default] dispinterface _DTestPresenceWebControl;
	};

};
